### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by yukukky** [yukukky/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by yukukky** [comment]
これから対応します。

**Comment by RCkukita** [comment]
e97572c で対応されました。

**Comment by yukukky** [comment]
e97572cで対応されました。
